=== Sevilda/DW9YG6MDbGyak/03.02/VE_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- gyokerelem feat keys -->
<xs:element name="DW9YG6" type="rootType">

	<!-- keys -->
	<xs:key name="key_etterem"> 
		<xs:selector xpath="etterem"></xs:selector>
		<xs:field xpath="@ekod"></xs:field>
	</xs:key>
	
	<xs:key name="key_foszakacs"> 
		<xs:selector xpath="foszakacs"></xs:selector>
		<xs:field xpath="@fszkod"></xs:field>
	</xs:key>
	
	<xs:key name="key_szakacs"> 
		<xs:selector xpath="szakacs"></xs:selector>
		<xs:field xpath="@szkod"></xs:field>
	</xs:key>
	
	<xs:key name="key_gzakornok"> 
		<xs:selector xpath="gyakornok"></xs:selector>
		<xs:field xpath="@gykod"></xs:field>
	</xs:key>
	
	<xs:key name="key_vendeg"> 
		<xs:selector xpath="vendeg"></xs:selector>
		<xs:field xpath="@vkod"></xs:field>
	</xs:key>
	
	<!-- TODO must be unique -->
	<xs:keyref name="k2_k1" refer="key_etterem">
		<xs:selector xpath="foszakacs"></xs:selector>
		<xs:field xpath="@fk_ekod"></xs:field>
	</xs:keyref>
	
	<xs:keyref name="k3_k1" refer="key_etterem">
		<xs:selector xpath="szakacs"></xs:selector>
		<xs:field xpath="@fk_ekod"></xs:field>
	</xs:keyref>
	
	<xs:keyref name="k4_k1" refer="key_etterem">
		<xs:selector xpath="gyakornok"></xs:selector>
		<xs:field xpath="@fk_ekod"></xs:field>
	</xs:keyref>
	
	<xs:keyref name="rendeles_etterem" refer="key_etterem">
		<xs:selector xpath="rendeles"></xs:selector>
		<xs:field xpath="@fk_ekod"></xs:field>
	</xs:keyref>
	
	<xs:keyref name="rendeles_vendeg" refer="key_vendeg">
		<xs:selector xpath="rendeles"></xs:selector>
		<xs:field xpath="@fk_vkod"></xs:field>
	</xs:keyref>
	
</xs:element>
		
	<xs:complexType name="rootType">
		<xs:sequence>
			<xs:element name="etterem" type="etteremType" maxOccurs="unbounded"></xs:element>
			<xs:element name="foszakacs" type="foszakacsType" maxOccurs="unbounded"></xs:element>
			<xs:element name="szakacs" type="szakacsType" maxOccurs="unbounded"></xs:element>
			<xs:element name="gyakornok" type="gyakornokType" maxOccurs="unbounded"></xs:element>
			<xs:element name="vendeg" type="vendegType" maxOccurs="unbounded"></xs:element>
			<xs:element name="rendeles" type="rendelesType" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:complexType name="etteremType">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"></xs:element>
			<xs:element name="csillag" type="xs:int"></xs:element>
			<xs:element name="cim" type="cimType"></xs:element>
		</xs:sequence>
		<xs:attribute name="ekod" type="xs:string"></xs:attribute>
	</xs:complexType>
	
		
	<xs:complexType name="foszakacsType">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"></xs:element>
			<xs:element name="eletkor" type="xs:int"></xs:element>
			<xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
		<xs:attribute name="fszkod" type="xs:string"></xs:attribute>
		<xs:attribute name="fk_ekod" type="xs:string"></xs:attribute>
	</xs:complexType>
	
	
	<xs:complexType name="szakacsType">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"></xs:element>
			<xs:element name="reszleg" type="xs:string"></xs:element>
			<xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
		<xs:attribute name="szkod" type="xs:string"></xs:attribute>
		<xs:attribute name="fk_ekod" type="xs:string"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="vendegType">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"></xs:element>
			<xs:element name="cim" type="cimType"></xs:element>
		</xs:sequence>
		<xs:attribute name="vkod" type="xs:string"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="gyakornokType">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"></xs:element>
			<xs:element name="muszak" type="xs:string" maxOccurs="unbounded"></xs:element>
			<xs:element name="gyakorlat" type="gyakorlatType"></xs:element>
		</xs:sequence>
		<xs:attribute name="gykod" type="xs:string"></xs:attribute>
		<xs:attribute name="fk_ekod" type="xs:string"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="rendelesType">
		<xs:sequence>
			<xs:element name="osszeg" type="xs:int"></xs:element>
			<xs:element name="etel" type="xs:string"></xs:element>
		</xs:sequence>
		<xs:attribute name="fk_ekod" type="xs:string"></xs:attribute>
		<xs:attribute name="fk_vkod" type="xs:string"></xs:attribute>
	</xs:complexType>
	

	<!-- additional types -->
	<xs:complexType name="gyakorlatType">
		<xs:sequence>
			<xs:element name="idotartam" type="xs:string"></xs:element>
			<xs:element name="kezdet" type="xs:date"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:complexType name="cimType">
		<xs:sequence>
			<xs:element name="varos" type="xs:string"></xs:element>
			<xs:element name="utca" type="xs:string"></xs:element>
			<xs:element name="hazszam" type="xs:int"></xs:element>
		</xs:sequence>
	</xs:complexType>
	

	
	
</xs:schema>

=== Sevilda/DW9YG6MDbGyak/02.23/ett.xml
<DW9YG6 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="VE_XMLSchema.xsd">

	<!---Ettermek -->
	<etterem ekod="e1">
		<nev> A </nev>
		<csillag> 2</csillag>
		<cim>
			<varos>Miskolc</varos>
			<utca>X</utca>
			<hazszam>42</hazszam>
		</cim>
	</etterem>
	<etterem ekod="e2">
		<nev>B </nev>
		<csillag> 3</csillag>
		<cim>
			<varos>Varbo</varos>
			<utca>Y</utca>
			<hazszam>69</hazszam>
		</cim>
	</etterem>
	
	<!---Foszakacsok -->
	<foszakacs fszkod="f1" fk_ekod="e1">
		<nev>Kis Laci</nev>
		<eletkor>55</eletkor>
		<vegzettseg>Szakkozep</vegzettseg>
		<vegzettseg>Szakkepzes</vegzettseg>
		<vegzettseg>Fejlesztes</vegzettseg>
	</foszakacs>
	<foszakacs fszkod="f2" fk_ekod="e2">
		<nev>Nagy Pisti</nev>
		<eletkor>19</eletkor>
		<vegzettseg>Szakkozep</vegzettseg>
		<vegzettseg>Szakkepzes</vegzettseg>
	</foszakacs>
	
	<!---Szakacsok -->
	<szakacs szkod="sz1" fk_ekod="e1">
		<nev>Kis Jany</nev>
		<reszleg>Elso</reszleg>
		<vegzettseg>Kozepiskola</vegzettseg>
	</szakacs>
	<szakacs szkod="sz2" fk_ekod="e1">
		<nev>Nagy Peti</nev>
		<reszleg>Elso</reszleg>
		<vegzettseg>Szakkepzes</vegzettseg>
	</szakacs>
	<szakacs szkod="sz3" fk_ekod="e1">
		<nev>Halasz Jani</nev>
		<reszleg>Masodik</reszleg>
		<vegzettseg>Semmi</vegzettseg>
	</szakacs>
	<szakacs szkod="sz4" fk_ekod="e2">
		<nev>Szolga Gyongy</nev>
		<reszleg>Mosogato</reszleg>
		<vegzettseg>Szakkozepiskola</vegzettseg>
		<vegzettseg>Szakkepzes</vegzettseg>
	</szakacs>
	
	<!---Gyakornokok -->
	<gyakornok gykod="gy1" fk_ekod="e1">
		<nev>Pelda Panna</nev>
		<muszak>nappali</muszak>
		<muszak>delutani</muszak>
		<gyakorlat>
			<idotartam>6 honap</idotartam>
			<kezdet>2022-03-06</kezdet>
		</gyakorlat>
	</gyakornok>
	<gyakornok gykod="gy2" fk_ekod="e1">
		<nev>Pelda K</nev>
		<muszak>reggeli</muszak>
		<muszak>delutani</muszak>
		<gyakorlat>
			<idotartam>3 honap</idotartam>
			<kezdet>2022-03-30</kezdet>
		</gyakorlat>
	</gyakornok>
	
	<!---Vendegek -->
	<vendeg vkod="v1">
		<nev>Toth Lenke</nev>
		<cim>
			<varos>Budapest</varos>
			<utca>Utcacska</utca>
			<hazszam>80</hazszam>
		</cim>
	</vendeg>
	<vendeg vkod="v2">
		<nev>Vadon E</nev>
		<cim>
			<varos>Miskolc</varos>
			<utca>Utca</utca>
			<hazszam>10</hazszam>
		</cim>
	</vendeg>
		<vendeg vkod="v3">
		<nev>Kiss Mari</nev>
		<cim>
			<varos>Miskolc</varos>
			<utca>Fõ</utca>
			<hazszam>420</hazszam>
		</cim>
	</vendeg>
		<vendeg vkod="v4">
		<nev>Nagy Medve</nev>
		<cim>
			<varos>Szerencs</varos>
			<utca>Mellék</utca>
			<hazszam>66</hazszam>
		</cim>
	</vendeg>
	
	<!---Rendelesek -->
	<rendeles fk_vkod="v1" fk_ekod="e1">
		<osszeg>64000</osszeg>
		<etel>Rantott rak</etel>
	</rendeles>
	<rendeles fk_vkod="v2" fk_ekod="e1">
		<osszeg>500</osszeg>
		<etel>Szodaviz</etel>
	</rendeles>
		<rendeles fk_vkod="v2" fk_ekod="e1">
		<osszeg>750</osszeg>
		<etel>Szodaviz</etel>
	</rendeles>
		<rendeles fk_vkod="v2" fk_ekod="e2">
		<osszeg>1000</osszeg>
		<etel>Kókuszkocka</etel>
	</rendeles>
	    <rendeles fk_vkod="v4" fk_ekod="e1">
		<osszeg>1000</osszeg>
		<etel>Kókuszkocka</etel>
	</rendeles>
		<rendeles fk_vkod="v4" fk_ekod="e2">
		<osszeg>1500</osszeg>
		<etel>Zserbó</etel>
	</rendeles>
		<rendeles fk_vkod="v3" fk_ekod="e2">
		<osszeg>2500</osszeg>
		<etel>Lángos</etel>
	</rendeles>


</DW9YG6>
